### PR TITLE
Filter out null gameVersionFlavor

### PR DESCRIPTION
**Pull request by petergam**

### CODE REVIEW

**Comment by petergam** [comment]
@casperstorm Can you help test the new catalog with the currently released version?
https://raw.githubusercontent.com/ajour/ajour-catalog/3317165971b0a48ce95435607de24666c5490f3c/catalog-2.0.json

**Comment by petergam** [comment]
I've just reverted the change to create a new catalog for now. With these changes the catalog should be compatible with the currently released versions.

We can then prepare for a new catalog that support more flavors that we will rollout with a new version of the client.

**Comment by casperstorm** [comment]
It does parse it correctly, however it seems theres duplicates in it.

Screenshot 2021-04-02 at 18 51 06

**Comment by petergam** [comment]
> It does parse it correctly, however it seems theres duplicates in it.
> 
> Screenshot 2021-04-02 at 18 51 06

Thanks for checking. I see the problem. I'll look into it

**Comment by petergam** [comment]
@casperstorm Should be fixed here:
https://raw.githubusercontent.com/ajour/ajour-catalog/ad4d667e80ffe08a65773c61e4fc20611b6d70c3/catalog-2.0.json

**Comment by casperstorm** [comment]
This now works flawlessly, @petergp.

**Review by casperstorm — APPROVED** [review]

**Pull request merged**
